# Make sure this is set to "kotlinforforge"
modLoader="kotlinforforge"
# Make sure this is set to the appropriate version range
loaderVersion="[1.6,)" # Require at least 1.6.x
# License is REQUIRED after 1.16
license='LGPL'

[[mods]]
modId="phoenix"
version="${file.jarVersion}"
displayName="Phoenix Project"
credits="The ExampleMod dev team"
authors="WildTan"
description='''
Example mod that uses Kotlin for Forge.
'''
[[dependencies.phoenix]]
    modId="forge"
    mandatory=true
    versionRange="[31.2,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.phoenix]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3]"
    ordering="NONE"
    side="BOTH"
